# [colors.bright]
# black = "#444b6a"
# blue = "#7da6ff"
# cyan = "#0db9d7"
# green = "#b9f27c"
# magenta = "#bb9af7"
# red = "#ff7a93"
# white = "#acb0d0"
# yellow = "#ff9e64"
#
# [colors.normal]
# black = "#32344a"
# blue = "#7aa2f7"
# cyan = "#449dab"
# green = "#9ece6a"
# magenta = "#ad8ee6"
# red = "#f7768e"
# white = "#9699a8"
# yellow = "#e0af68"
#
# [colors.primary]
# background = "#24283b"
# foreground = "#a9b1d6"

# Default colors
[colors.primary]
background = '#24283b'
foreground = '#c0caf5'

# Normal colors
[colors.normal]
black = '#1d202f'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#a9b1d6'

# Bright colors
[colors.bright]
black = '#414868'
red = '#ff899d'
green = '#9fe044'
yellow = '#faba4a'
blue = '#8db0ff'
magenta = '#c7a9ff'
cyan = '#a4daff'
white = '#c0caf5'
